#!/bin/sh
set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d ebtables remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


if [ "$1" = "purge" ]; then
  rm -f /etc/ebtables.filter* /etc/ebtables.nat* /etc/ebtables.broute*
fi

exit 0
