#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove oslo-rootwrap /usr/bin/python2-oslo-rootwrap
	update-alternatives --remove oslo-rootwrap-daemon /usr/bin/python2-oslo-rootwrap-daemon
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-oslo.rootwrap 
else
	dpkg -L python-oslo.rootwrap | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
