#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove ryu /usr/bin/python2-ryu
	update-alternatives --remove ryu-manager /usr/bin/python2-ryu-manager
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-ryu 
else
	dpkg -L python-ryu | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
