#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/oslo-rootwrap oslo-rootwrap /usr/bin/python2-oslo-rootwrap 300
	update-alternatives --install /usr/bin/oslo-rootwrap-daemon oslo-rootwrap-daemon /usr/bin/python2-oslo-rootwrap-daemon 300
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-oslo.rootwrap 
fi

# End automatically added section


exit 0
