#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove oslo-config-generator /usr/bin/python2-oslo-config-generator
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-oslo.config 
else
	dpkg -L python-oslo.config | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
