#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove gunicorn_pecan /usr/bin/gunicorn_pecan-python2
	update-alternatives --remove pecan /usr/bin/pecan-python2
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-pecan 
else
	dpkg -L python-pecan | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
