#!/bin/sh
set -e

case "$1" in
    upgrade)
        # Work around symlink file to symlink directory (Debian bug #747088)
        rm -rf /usr/lib/python2*/dist-packages/appdirs-1.3.0.egg-info
    ;;
esac


# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-appdirs 
else
	dpkg -L python-appdirs | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

