#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/migrate migrate /usr/bin/python2-migrate 300
	update-alternatives --install /usr/bin/migrate-repository migrate-repository /usr/bin/python2-migrate-repository 300
fi


# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-migrate 
fi

# End automatically added section


exit 0
